### PR TITLE
fix SendEditableCode to add after current cell

### LINKED ISSUE #3759: When using SendEditableCode, the new cell should be added after the cell executing the code rather than the end

### PR DESCRIPTION
**Pull request by jonsequitur**
This fixes #3759.

### CODE REVIEW

File: src/polyglot-notebooks-vscode-common/src/metadataUtilities.ts [hunk 1]
```diff
@@ -281,6 +279,8 @@ export function getKernelspecMetadataFromNotebookDocumentMetadata(notebookDocume
 export function createNewIpynbMetadataWithNotebookDocumentMetadata(existingMetadata: { [key: string]: any }, notebookDocumentMetadata: NotebookDocumentMetadata): { [key: string]: any } {
     const resultMetadata: { [key: string]: any } = { ...existingMetadata };
 
+    // FIX: "custom" actually means just the bucket of things we don't persist, and therefore should not cause the document dirty state to be set
```
Comment (shyamnamboodiripad) [inline src/polyglot-notebooks-vscode-common/src/metadataUtilities.ts:282]: minor: Is this something you intended to address before merging this PR or is this just todo placeholder for a future fix?

**Review by shyamnamboodiripad — APPROVED** [review]

File: src/polyglot-notebooks-vscode-common/src/metadataUtilities.ts (hunk 1 above)
Comment (jonsequitur) [reply src/polyglot-notebooks-vscode-common/src/metadataUtilities.ts:282]: These are notes and placeholders for future fixes.
