### PR TITLE
properly classify markdown cells

### LINKED ISSUE #487: In VS Code extensions markdown should
### Describe the bug
When loading .dib files markdown cells are changed to .NET interactive. Cells are not evaluated correctly and the user experience is compromised (cannot collapse or render)

### Please complete the following:

**Which version of .NET Interactive are you using?** 
1.0.127302

- OS
    - [X] Windows 10
    - [ ] macOS
    - [ ] Linux (Please specify distro)
    - [ ] iOS
    - [ ] Android
 - Browser 
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
 - Frontend
    - [ ] Jupyter Notebook
    - [ ] Jupyter Lab
    - [ ] nteract
    - [X] Visual Studio Code
    - [ ] Other (please specify)

### Screenshots
image

### PR DESCRIPTION
**Pull request by brettfo**
Fixes #487.

### CODE REVIEW

File: src/dotnet-interactive-vscode/src/interactiveNotebook.ts [hunk 1]
```diff
@@ -136,6 +137,15 @@ export function serializeNotebook(notebook: NotebookFile): string {
     return lines.join('\r\n');
 }
 
+export function languageToCellKind(language: string): CellKind {
+    switch (language) {
+        case 'dotnet-interactive.markdown':
```
Comment (jonsequitur) [inline src/dotnet-interactive-vscode/src/interactiveNotebook.ts:142]: Do we need our own Markdown language identifier?

Comment (brettfo) [reply src/dotnet-interactive-vscode/src/interactiveNotebook.ts:142]: Yes.  In a polyglot file/cell, that's the classification that gets applied when `#!markdown` or `#!md` is encountered and we need it to be able to properly switch to another language or mark magic commands.
