### PR TITLE
if .ipynb document metadata isn't present, fall back to interpreting the kernelspec

### LINKED ISSUE #2685: Polyglot VSCode thinks F# notebooks generated by FSharp.Formatting are C# notebooks
### Describe the bug

1. This is probably the same issue as #2289, and it breaks all documentation notebooks previously created by F# Formatting.
2. For new F# notebooks, I can do a PR to update the F# Formatting library to generate F# notebooks with the metadata that the Polyglot notebooks extension wants. What metadata should we add?

Details follow:

The [F# Formatting Library](https://github.com/fsprojects/FSharp.Formatting) generates .NET interactive notebooks. The VSCode extension previously recognized the code cells as F#, but now the polyglot extension converts them to C#. As far as I can tell it's necessary to manually go through every cell and change it to F# (not practical). This breaks all documentation notebooks previously created by F# Formatting.

For example, the extension now thinks the F# code in [this notebook](https://fsprojects.github.io/FSharp.Data//library/CsvProvider.ipynb) from the [F# Data Library](https://github.com/fsprojects/FSharp.Data) is C# code:

image

Regarding metadata ... A simple notebook generated by the F# formatting tool looks like this below in json and is what used to work with the old VSCode extension.

```json
        {
            "cells": [
          {
           "cell_type": "code",
           "metadata": {},
            "execution_count": 1, "outputs": [],
           "source": ["let x = 100\n"]
          }
,
          {
           "cell_type": "code",
           "metadata": {},
            "execution_count": 2, "outputs": [],
           "source": ["let y = 100\n"]
          }],
            "metadata": {
            "kernelspec": {"display_name": ".NET (F#)", "language": "F#", "name": ".net-fsharp"},
            "langauge_info": {
        "file_extension": ".fs",
        "mimetype": "text/x-fsharp",
        "name": "C#",
        "pygments_lexer": "fsharp",
        "version": "4.5"
        }
        },
            "nbformat": 4,
            "nbformat_minor": 1
        }
```

From experimentation, it looks like if we change `"metadata": {}` in code cells to what I have here then the cells are recognized as being F# code. Is this correct, is there anything else that you suggest?
```json
 "metadata": {
    "dotnet_interactive": {
     "language": "fsharp"
    },
    "polyglot_notebook": {
     "kernelName": "fsharp"
    }
   }
```

### Please complete the following:

**Which version of .NET Interactive are you using?** (In a notebook, run the `#!about` magic command. ):

.NET Interactive
Version: 1.0.360602+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Library version: 1.0.0-beta.22606.2+9bf026dabac44a6256a65168fa93dcb7e2edcca4
Build date: 2023-01-31T11:33:36.0115292Z

### PR DESCRIPTION
**Pull request by brettfo**
If a cell doesn't have kernel metadata, fall back to using the document's metadata, and if the document doesn't have the appropriate metadata, re-create it from the kernelspec.

This bug was only in the VS Code extension; the document APIs already has a test for exactly this scenario [here](https://github.com/dotnet/interactive/blob/208167e09a6ae48311e1e20bd21bda1068fb8429/src/Microsoft.DotNet.Interactive.Documents.Tests/JupyterFormatTests.cs#L40).

Fixes #2685.

### CODE REVIEW

File: src/dotnet-interactive-vscode-common/src/notebookCellStatusBarItemProvider.ts [hunk 1]
```diff
@@ -78,8 +78,9 @@ class DotNetNotebookCellStatusBarItemProvider {
             return [];
         }
 
+        const notebookMetadata = metadataUtilities.getNotebookDocumentMetadataFromNotebookDocument(cell.notebook);
         const cellMetadata = metadataUtilities.getNotebookCellMetadataFromNotebookCellElement(cell);
-        const cellKernelName = cellMetadata.kernelName ?? 'csharp';
+        const cellKernelName = cellMetadata.kernelName ?? notebookMetadata.kernelInfo.defaultKernelName;
```
Comment (brettfo) [inline src/dotnet-interactive-vscode-common/src/notebookCellStatusBarItemProvider.ts:83]: This is the core of the fix; everything else is just making sure we have something meaningful here.

File: src/dotnet-interactive-vscode-insiders/src/notebookControllers.ts [hunk 2]
```diff
@@ -83,14 +83,12 @@ export class DotNetNotebookKernel {
...
+                    if (foundCell) {
+                        // if we found the cell ensure it has kernel metadata
                         const cellMetadata = metadataUtilities.getNotebookCellMetadataFromNotebookCellElement(foundCell);
                         if (!cellMetadata.kernelName) {
-                            // no kernel metadata; copy from previous cell
-                            const previousCell = cells[foundCell.index - 1];
-                            const previousCellMetadata = metadataUtilities.getNotebookCellMetadataFromNotebookCellElement(previousCell);
-                            await vscodeUtilities.setCellKernelName(foundCell, previousCellMetadata.kernelName ?? notebookMetadata.kernelInfo.defaultKernelName);
+                            // no kernel name; set it from the notebook metadata
+                            await vscodeUtilities.setCellKernelName(foundCell, notebookMetadata.kernelInfo.defaultKernelName);
```
Comment (brettfo) [inline src/dotnet-interactive-vscode-insiders/src/notebookControllers.ts:91]: This is part 2 of the core fix; when we first open a document, we ensure each cell has a kernel name set.

**Review by jonsequitur — APPROVED** [review]

**Review by colombod — APPROVED** [review]
